name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 24.3
          - 24.5
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - 29.4
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v4
    - name: Run tests
      run: make
